DROP DATABASE IF EXISTS company_db;
CREATE DATABASE company_db;

USE company_db

CREATE TABLE department (
id INT PRIMARY KEY,
name VARCHAR(30) NOT NULL
):

CREATE TABLE roles(
ID NOT NULL AUTO INCREMENT PRIMARY KEY,
id: INT PRIMARY KEY, NOT NULL
title: VARCHAR(30),
salary: DECIMAL NOT NULL,
department_id: INT,
FOREIGN KEY (department_id) 
REFERENCES departments(id)
ON DELETE SET NULL
);

CREATE TABLE employees (
ID NOT NULL AUTO INCREMENT PRIMARY KEY,
first_name: VARCHAR(30) NOT NULL,
last_name: VARCHAR(30) NOT NULL,
role_id:INT,
manager_id:INT,NULL
FOREIGN KEY (role_id) 
REFERENCES roles(id),
FOREIGN KEY (manager_id) 
REFERENCES employees(id)
ON DELETE SET NULL,
);